[projects.puzzle1]
files = ["puzzle1.poni"]
imports = ["../read_file.h"]

[projects.puzzle2]
files = ["puzzle2.poni"]
imports = ["../read_file.h"]

[projects.puzzle2-2]
files = ["puzzle2-2.poni"]
imports = ["../read_file.h"]
