[projects.puzzle1]
files = ["puzzle1.poni"]
imports = ["../read_file.h"]

[projects.puzzle2]
files = ["puzzle2.poni"]
imports = ["../read_file.h"]

[projects.puzzle1-dynarray]
files = ["puzzle1-dynarray.poni"]
imports = ["../read_file.h"]

[projects.puzzle2-dynarray]
files = ["puzzle2-dynarray.poni"]
imports = ["../read_file.h"]